
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # These services rely on expected container available DI injections.
  # Other services are loaded in the CrayfishCommonsExtension class.
  Islandora\Crayfish\Commons\CmdExecuteService: ~

  Islandora\Crayfish\Commons\EntityMapper\:
    resource: '../../EntityMapper/*'

  Islandora\Crayfish\Commons\ApixMiddleware:
    tags:
    - { name: kernel.event_subscriber, event: kernel.request }

  # Aliases, if the class has not yet been instantiated it will be
  # in CrayfishCommonsExtension class
  crayfish.cmd_execute_service:
    alias: Islandora\Crayfish\Commons\CmdExecuteService

  # Map the concrete class to the interface.
  Islandora\Crayfish\Commons\EntityMapper\EntityMapperInterface: '@Islandora\Crayfish\Commons\EntityMapper\EntityMapper'
